language: python
python:
- '3.6'
before_install:
- pip install poetry
install:
- poetry install -v
before_deploy:
- poetry config http-basic.pypi __token__ ${{ secrets.PYPI_TOKEN }}
- poetry build
deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
